### ISSUE TITLE
NodeBots Jan 2015

### ISSUE THREAD

**Issue by achingbrain** [nodebots/london#4]
- [x] Date? Sunday 31st Jan
- [x] Tickets?  £5
- [x] Capacity? 20
- [x] Lunch?
- [x] Talk?

**Comment by olizilla** [comment]
:+1: I'm down for cook lunch again. Maybe a meatmon event, with live meat readings?

**Comment by achingbrain** [comment]
I'm up for Meatmoning at a NodeBots but I think it's probably better left for the summer months as to have it ready for lunch we'd have to light the fire at about 4am.  Also £5pp would be a stretch.  NodeBots Day 2016 for sure though.

**Comment by achingbrain** [comment]
Lunch - @alanshaw
Talks - @achingbrain
